In [21]:
from __future__ import print_function
import pandas as pd
import numpy as np
import math
#Vamos importar o solver linear do ORTOOLS

from ortools.linear_solver import pywraplp
#Vamos importar o numpy como uma ferramenta auxiliar 


solver = pywraplp.Solver.CreateSolver('SCIP')

def mi2ai(i,j,line_length):
	return i*N+j

def ai2mi(index, line_length):
	return [maph.floor(index/line_length), index%line_length]
sla = {}
OMA = list()
NOMA = list()
FixNOMA = list()
OUTAGE = list()
NOMA_PAIRS = list()
FNOMA_PAIRS = list()

def ajuste(tabela):
	tabela.index = tabela.columns
	asd = sorted(list(tabela.columns))
	tabela = tabela.reindex(asd,axis=1)
	tabela = tabela.reindex(asd,axis=0)
	return tabela	


In [22]:
NUFNOMA = pd.read_csv('0DF4.csv')
NUFNOMA = NUFNOMA.drop(['Unnamed: 0'],axis=1)
NUFNOMA.index = NUFNOMA.columns
asd = sorted(list(NUFNOMA.columns))
NUFNOMA = NUFNOMA.reindex(asd,axis=1)
NUFNOMA = NUFNOMA.reindex(asd,axis=0)
print(NUFNOMA.head(10))

           0         1         2         3          4         5         6  \
0   4.000000  3.877443  0.894718  7.945671   1.679706  0.000000  5.996318   
1  25.045467  1.000000  0.894718  7.945671   1.679706  2.729718  5.996318   
2   0.000000  0.000000  4.000000  0.000000   0.000000  0.000000  0.000000   
3  25.045467  3.877443  0.894718  2.000000   1.679706  2.729718  5.996318   
4   0.000000  0.000000  0.000000  0.000000  16.000000  0.000000  0.000000   
5  25.045467  3.877443  0.894718  7.945671   1.679706  2.000000  5.996318   
6   0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  8.000000   
7   0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000   
9  25.045467  3.877443  0.894718  7.945671   1.679706  2.729718  5.996318   

          7          8          9  
0  29.93063  19.123759  11.385056  
1  29.93063  19.123759  11.385056  
2   0.00000   0.000000   0.000000  
3  29.93

In [23]:
FNOMA = pd.read_csv('0DF3.csv')
FNOMA = FNOMA.drop(['Unnamed: 0'],axis=1)
FNOMA.index = FNOMA.columns
asd = sorted(list(FNOMA.columns))
FNOMA = FNOMA.reindex(asd,axis=1)
FNOMA = FNOMA.reindex(asd,axis=0)
FNOMA.head(10)

0         1         2         3          4         5         6  \
0  4.000000  2.000000  2.000000  2.000000   2.000000  0.000000  2.000000   
1  1.924433  1.000000  1.924433  1.924433   1.924433  1.924433  1.924433   
2  0.000000  0.000000  4.000000  0.000000   0.000000  0.000000  0.000000   
3  1.995604  1.995604  1.995604  2.000000   1.995604  1.995604  1.995604   
4  0.000000  0.000000  0.000000  0.000000  16.000000  0.000000  0.000000   
5  1.826898  1.826898  1.826898  1.826898   1.826898  2.000000  1.826898   
6  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  8.000000   
7  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000   
9  1.999595  1.999595  1.999595  1.999595   1.999595  1.999595  1.999595   

           7          8         9  
0   2.000000   2.000000  2.000000  
1   1.924433   1.924433  1.924433  
2   0.000000   0.000000  0.000000  
3   1.995604   1.995604  1.995604  
4   0.000000   0.000000  0.000000  
5   1.826898   1.826898  1.826898  
6   0.000000   0.000000  0.000000  
7  32.000000   0.000000  0.000000  
8   0.000000  32.000000  0.000000  
9   1.999595   1.999595  2.000000

In [24]:
DATA = pd.read_csv('DATA.csv')
DATA

DF_OMA = pd.read_csv('0DF1.csv')

DF_OMA = DF_OMA.drop(['Unnamed: 0'],axis=1)
DF_OMA.index = DF_OMA.columns
asd = sorted(list(DF_OMA.columns))
DF_OMA = DF_OMA.reindex(asd,axis=1)
DF_OMA = DF_OMA.reindex(asd,axis=0)
#print(DF_OMA)

DF_NOMA = pd.read_csv('0DF.csv')
DF_NOMA = DF_NOMA.drop(['Unnamed: 0'],axis=1)
DF_NOMA.index = DF_NOMA.columns
asd = sorted(list(DF_NOMA.columns))
DF_NOMA = DF_NOMA.reindex(asd,axis=1)
DF_NOMA = DF_NOMA.reindex(asd,axis=0)
#DF_NOMA.head(10)

DF2 = pd.read_csv('0DF2.csv')
DF2['Unnamed: 0'] = DF2.columns[1:]
DF2.rename(columns = {'Unnamed: 0':'SUMRATE FU-NU'}, inplace = True)
DF2 = DF2.set_index(DF2['SUMRATE FU-NU'])
DF2 = DF2.drop(['SUMRATE FU-NU'],axis=1)
asd = sorted(list(DF2.columns))
DF2 = DF2.reindex(asd,axis=1)
DF2 = DF2.reindex(asd,axis=0)
#print(DF2.head(10))


In [25]:
DF2

0         1          2          3          4         5  \
SUMRATE FU-NU                                                                   
0               4.000000  6.775780  27.045467  10.354842  27.045467  0.000000   
1               9.801867  1.000000   5.801876   7.578639   5.801876  4.749753   
2               0.000000  0.000000   4.000000   0.000000   0.000000  0.000000   
3              13.941122  6.698935   9.941276   2.000000   9.941276  4.899485   
4               0.000000  0.000000   0.000000   0.000000  16.000000  0.000000   
5               8.556613  5.059613   4.556616   6.460587   4.556616  2.000000   
6               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
7               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
8               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
9              17.382982  6.768543  13.384652  10.311476  13.384652  4.908130   

                       6          7          8          9  
SUMRATE FU-NU                                              
0              27.045467  27.045467  27.045467  13.799517  
1               5.801876   5.801876   5.801876   7.779871  
2               0.000000   0.000000   0.000000   0.000000  
3               9.941276   9.941276   9.941276  11.590185  
4               0.000000   0.000000   0.000000   0.000000  
5               4.556616   4.556616   4.556616   6.547525  
6               8.000000   0.000000   0.000000   0.000000  
7               0.000000  32.000000   0.000000   0.000000  
8               0.000000   0.000000  32.000000   0.000000  
9              13.384652  13.384652  13.384652   2.000000

In [26]:
DF_NOMA

0         1          2         3          4         5          6  \
0   4.000000  5.775780  27.045467  8.354842  27.045467  0.000000  27.045467   
1   5.801867  1.000000   5.801876  5.578639   5.801876  2.749753   5.801876   
2   0.000000  0.000000   4.000000  0.000000   0.000000  0.000000   0.000000   
3   9.941122  5.698935   9.941276  2.000000   9.941276  2.899485   9.941276   
4   0.000000  0.000000   0.000000  0.000000  16.000000  0.000000   0.000000   
5   4.556613  4.059613   4.556616  4.460587   4.556616  2.000000   4.556616   
6   0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   8.000000   
7   0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   0.000000   
8   0.000000  0.000000   0.000000  0.000000   0.000000  0.000000   0.000000   
9  13.382982  5.768543  13.384652  8.311476  13.384652  2.908130  13.384652   

           7          8          9  
0  27.045467  27.045467  11.799517  
1   5.801876   5.801876   5.779871  
2   0.000000   0.000000   0.000000  
3   9.941276   9.941276   9.590185  
4   0.000000   0.000000   0.000000  
5   4.556616   4.556616   4.547525  
6   0.000000   0.000000   0.000000  
7  32.000000   0.000000   0.000000  
8   0.000000  32.000000   0.000000  
9  13.384652  13.384652   2.000000

In [27]:
Channel_Capacity = np.diag(DF_OMA) #Capacidade do canal

Baseline = ajuste(pd.read_csv('Baseline.csv',index_col=0))
User_Demand = np.diag(DF_NOMA) #Demanda do Usuário
User_Demand[0]
N = len(Channel_Capacity)
IM = np.zeros((N,N))
DF_NOMA = np.matrix(DF2)

for i in range(N):
    for j in range(N):
        if i == j:
            IM[i,j] = User_Demand[i]
            if Channel_Capacity[i]<IM[i,j]:
                IM[i,j] = Channel_Capacity[i]
            else:
                pass
        else:
            IM[i,j] = DF_NOMA[i,j]       

for i in range(N):
    for j in range(N):
        if i == j:
            IM[i,j] = User_Demand[i]
            if Channel_Capacity[i]<DF_NOMA[i,j]:
                IM[i,j] = Channel_Capacity[i]
            else:
                pass
        else:
            DF_NOMA[i,j] = DF_NOMA[i,j] 

           

for i in range(N):
    for j in range(N):
        if i == j:
            pass
        else:
            #print(f'{IM[i,i]+IM[j,j]} < {IM[j,i]} = {IM[i,i]<= IM[j,i]}')
            if IM[i,i]+IM[j,j]<= IM[j,i]:
                pass
            else:
                IM[j,i] = 0
            
#print(IM)             
    

In [28]:
#DF_NOMA = np.matrix(DF_NOMA)
DF_NOMA

matrix([[ 4.        ,  6.77578029, 27.04546747, 10.35484176, 27.04546747,
          0.        , 27.04546747, 27.04546747, 27.04546747, 13.79951711],
        [ 9.80186731,  1.        ,  5.80187587,  7.57863937,  5.80187587,
          4.74975256,  5.80187587,  5.80187587,  5.80187587,  7.77987085],
        [ 0.        ,  0.        ,  4.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [13.94112238,  6.69893546,  9.94127582,  2.        ,  9.94127582,
          4.89948496,  9.94127582,  9.94127582,  9.94127582, 11.59018501],
        [ 0.        ,  0.        ,  0.        ,  0.        , 16.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 8.55661251,  5.05961276,  4.55661603,  6.46058724,  4.55661603,
          2.        ,  4.55661603,  4.55661603,  4.55661603,  6.54752516],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  8.       

In [29]:
Baseline = np.matrix(Baseline)

for i in range(N):
    for j in range(N):
        if i == j:
            Baseline[i,j] = User_Demand[i]
            if Channel_Capacity[i]<Baseline[i,j]:
                Baseline[i,j] = Channel_Capacity[i]
            else:
                pass
        else:
            Baseline[i,j] = Baseline[i,j] 

In [30]:
pd.DataFrame(Baseline)

0         1          2          3          4         5          6  \
0   4.000000  6.775780  27.045467  10.354842  27.045467  0.000000  27.045467   
1   9.801867  1.000000   5.801876   7.578639   5.801876  4.749753   5.801876   
2   0.000000  0.000000   2.149581   0.000000   0.000000  0.000000   0.000000   
3  13.941122  6.698935   9.941276   2.000000   9.941276  4.899485   9.941276   
4   0.000000  0.000000   0.000000   0.000000   3.294915  0.000000   0.000000   
5   8.556613  5.059613   4.556616   6.460587   4.556616  2.000000   4.556616   
6   0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   7.979268   
7   0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   0.000000   
8   0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   0.000000   
9  17.382982  6.768543  13.384652  10.311476  13.384652  4.908130  13.384652   

           7          8          9  
0  27.045467  27.045467  13.799517  
1   5.801876   5.801876   7.779871  
2   0.000000   0.000000   0.000000  
3   9.941276   9.941276  11.590185  
4   0.000000   0.000000   0.000000  
5   4.556616   4.556616   6.547525  
6   0.000000   0.000000   0.000000  
7  31.930630   0.000000   0.000000  
8   0.000000  21.123757   0.000000  
9  13.384652  13.384652   2.000000

In [31]:
pd.DataFrame(DF2)

0         1          2          3          4         5  \
SUMRATE FU-NU                                                                   
0               4.000000  6.775780  27.045467  10.354842  27.045467  0.000000   
1               9.801867  1.000000   5.801876   7.578639   5.801876  4.749753   
2               0.000000  0.000000   4.000000   0.000000   0.000000  0.000000   
3              13.941122  6.698935   9.941276   2.000000   9.941276  4.899485   
4               0.000000  0.000000   0.000000   0.000000  16.000000  0.000000   
5               8.556613  5.059613   4.556616   6.460587   4.556616  2.000000   
6               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
7               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
8               0.000000  0.000000   0.000000   0.000000   0.000000  0.000000   
9              17.382982  6.768543  13.384652  10.311476  13.384652  4.908130   

                       6          7          8          9  
SUMRATE FU-NU                                              
0              27.045467  27.045467  27.045467  13.799517  
1               5.801876   5.801876   5.801876   7.779871  
2               0.000000   0.000000   0.000000   0.000000  
3               9.941276   9.941276   9.941276  11.590185  
4               0.000000   0.000000   0.000000   0.000000  
5               4.556616   4.556616   4.556616   6.547525  
6               8.000000   0.000000   0.000000   0.000000  
7               0.000000  32.000000   0.000000   0.000000  
8               0.000000   0.000000  32.000000   0.000000  
9              13.384652  13.384652  13.384652   2.000000

Criando as Variaveis: N Variaveis de usuários primários
                      NxN Variaveis de usuários secundários

In [32]:
def TA(DF0,DF1,DF2,DF3,DF4,DF5):
	DF_NOMA = ajuste(DF0)
	DF1 = ajuste(DF1)
	DF2 = ajuste(DF2)
	DF3 = ajuste(DF3)
	DF4 = ajuste(DF4)
	DF5 = ajuste(DF5)
	Channel_Capacity = np.diag(DF1) #Capacidade do canal

	Baseline = DF5
	User_Demand = np.diag(DF0) #Demanda do Usuário
	User_Demand[0]
	N = len(Channel_Capacity)
	IM = np.zeros((N,N))
	DF_NOMA = np.matrix(DF_NOMA)
	DF2= np.matrix(DF2)
	print(Channel_Capacity)
	'''	for i in range(N):
			for j in range(N):
				if i == j:
					
					if Channel_Capacity[i]<DF2[i,j]:
						IM[i,j] = Channel_Capacity[i]
					else:
						IM[i,j] = User_Demand[i]
				else:
					IM[i,j] = DF_NOMA[i,j]   '''    

	for i in range(N):
		for j in range(N):
			if i == j:
				IM[i,j] = User_Demand[i]
				#print(f'{Channel_Capacity[i]}<{IM[i,j]}')
				if Channel_Capacity[i]<IM[i,j]:
					IM[i,j] = Channel_Capacity[i]
					#print(f'Trocou indice {i},{j}, antes era {User_Demand[i]}, agora é {IM[i,j]} ')
				else:
					pass
			else:
				IM[i,j] = DF_NOMA[i,j] 

	for i in range(N):
		for j in range(N):
			if i == j:
				pass
			else:
				if IM[i,i]+IM[j,j]<= IM[i,j]:
					pass
				else:
					IM[i,j] = 0
					
	Baseline = np.matrix(Baseline)

	for i in range(N):
		for j in range(N):
			if i == j:
				Baseline[i,i] = User_Demand[i]
				if Channel_Capacity[i]<Baseline[i,i]:
					Baseline[i,j] = Channel_Capacity[i]
				else:
					pass
			else:
				Baseline[i,j] = Baseline[i,j] 
	solver = pywraplp.Solver.CreateSolver('SCIP')
	FU = list()
	for i in range(0,N):
		for j in range(0,N):
			FU.append(solver.IntVar(0, 1,f'FU_{i}_{j}'))


	head = 1

	for j in range(N):
		ct = solver.Constraint(1,1,str(head))
		#print(f'Restrição {head}:')
		for i in range(N):
			if i == j:
				ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
				#print(f'{FU[mi2ai(j,i,N)]}+',end='')
			else:
				ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
				#print(f'{FU[mi2ai(j,i,N)]}+',end='')
				ct.SetCoefficient(FU[mi2ai(i,j,N)], 1)
				#if i == N-1:
					#print(f'{FU[mi2ai(i,j,N)]}')
				#else:
					#print(f'{FU[mi2ai(i,j,N)]}+',end='')
		head +=1	

	ct = solver.Constraint(N,N,str(head))
	#print(f'Restrição {head}')
	for i in range(N):
		for j in range(N):
			if i ==j:
				ct.SetCoefficient(FU[mi2ai(i,j,N)], 1)
			else:
				ct.SetCoefficient(FU[mi2ai(i,j,N)], 2)
				
			#if i  == N-1 and j ==N-1:
				#print(f'{FU[mi2ai(i,j,N)]} == {N}')
			#else:
				#print(f'{FU[mi2ai(i,j,N)]}+',end='')

				
	# #Executaremos o solver
	objective = solver.Objective()
	for j in range(N):
		for i in range(N):
			objective.SetCoefficient(FU[mi2ai(i,j,N)], IM[i,j])

	objective.SetMaximization()

	solver.Solve()

	#print('Solution:')
	#print('Valor objetivo =', (objective.Value()))
	pair = 0
	matriz = np.zeros(shape=(N,N))
	Fmatriz = np.zeros(shape=(N,N))
	Omatriz = np.zeros(shape=(N,N))
	matriz1 = np.zeros(shape=(N,N))
	conta=0
	for i in range(0,N):
		for j in range(0,N):
			matriz[i,j] = (int(FU[mi2ai(i,j,N)].solution_value()))
			conta +=(int(FU[mi2ai(i,j,N)].solution_value()))
	for i in range(0,N):
		for j in range(0,N):
			if i != j:
				matriz[i,j] = (int(FU[mi2ai(i,j,N)].solution_value()))
				conta +=(int(FU[mi2ai(i,j,N)].solution_value()))
				if int(FU[mi2ai(i,j,N)].solution_value()) ==1:
						matriz[i,i] = 0
						matriz[j,j] = 0
	usuario_atendido = list(DF1.columns)
	tot = 0
	ftot = 0
	outage = 0
	NomaP= 0
	FNomaP = 0
	print(f'Conta AHNOMA = {conta}')
	for i in range(0,N):
		for j in range(0,N):
			
			if matriz[i,j] ==1:
				if i == j:
					Omatriz[i,j]=1
					Fmatriz[i,j]=1
					#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
					#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
					usuario_atendido.remove(DF1.columns[j])
					tot +=IM[i,i]
					ftot += IM[i,i]
					#print(Aloc[i,j])
					#ftot += FNOMA.iloc[i,j]
				else:
					#print(f'NOMA Pair {pair} Near  User: {FU[j]}, data rate = {Aloc[j,j]}') 
					#print(f'NOMA Pair {pair} Far  User: {FU[i]}, data rate = {DF_NOMA.iloc[i,j]}')
					NomaP +=1
					#print(f'FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
					#print(f'FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
					#print(f'Gain over OMA:{(Aloc.iloc[i,j]/np.diag(Aloc)[j])*100}% ') 
					#print(Aloc[i,j])
					
					
					tot +=IM[i,j]
					if DF3.iloc[i,j] >= DF_NOMA[i,i] and DF4.iloc[j,j] >= DF_NOMA[j,j]:
						#print(f'alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
						#print(f'alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
						FNomaP +=1
						ftot += DF4.iloc[i,j]
						ftot += DF3.iloc[j,j]
						#print(Aloc[i,j])
						Fmatriz[i,j]=1
						#usuario_atendido.remove(DF_NOMA.columns[j])
						#usuario_atendido.remove(DF_NOMA.index[i])
						
					else:
						#print(f'Não alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[j,j]}') 
						#print(f'Não alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[i,i]}')
						outage +=1
						Fmatriz[i,i]=1
						Fmatriz[j,j]=1
						Fmatriz[i,j]=0
						#print(Aloc[i,j])
						#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
						#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
						#usuario_atendido.remove(DF_NOMA.columns[j])
						tot +=DF_NOMA[j,i]
						ftot += DF4.iloc[i,j]
						ftot += DF3.iloc[i,j]
						pass
					pair = pair +1
			else:
				Omatriz[i,i]=1

	matriz1 = matriz

	solver1 = pywraplp.Solver.CreateSolver('SCIP')
	FU1 = list()
	for i in range(0,N):
		for j in range(0,N):
			FU1.append(solver1.IntVar(0, 1,f'FU_{i}_{j}'))
	#print ('Numero de variaveis =', solver1.NumVariables())

	head = 1

	for j in range(N):
		ct1 = solver1.Constraint(1,1,str(head))
		#print(f'Restrição {head}:')
		for i in range(N):
			if i == j:
				ct1.SetCoefficient(FU1[mi2ai(i,i,N)], 1)
				#print(f'{FU[mi2ai(j,i,N)]}+',end='')
			else:
				ct1.SetCoefficient(FU1[mi2ai(j,i,N)], 1)
				#print(f'{FU[mi2ai(j,i,N)]}+',end='')
				ct1.SetCoefficient(FU1[mi2ai(i,j,N)], 1)
				#if i == N-1:
					#print(f'{FU[mi2ai(i,j,N)]}')
				#else:
					#print(f'{FU[mi2ai(i,j,N)]}+',end='')
		head +=1	

	ct1 = solver1.Constraint(N,N,str(head))
	#print(f'Restrição {head}')
	for i in range(N):
		for j in range(N):
			if i ==j:
				ct1.SetCoefficient(FU1[mi2ai(i,j,N)], 1)
			else:
				ct1.SetCoefficient(FU1[mi2ai(i,j,N)], 2)
				
			#if i  == N-1 and j ==N-1:
				#print(f'{FU[mi2ai(i,j,N)]} == {N}')
			#else:
				#print(f'{FU[mi2ai(i,j,N)]}+',end='')

				
	# #Executaremos o solver
	objective1 = solver1.Objective()
	for j in range(N):
		for i in range(N):
			objective1.SetCoefficient(FU1[mi2ai(i,j,N)], Baseline[i,j])

			
			
			
			#ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
	objective1.SetMaximization()

	solver1.Solve()

	print('Solution:')
	print('Valor objetivo BaseLine =', (objective1.Value()))
	print('Valor objetivo AHNOMA =', (objective.Value()))
	pair = 0
	matriz = np.zeros(shape=(N,N))
	conta = 0
	Fmatriz = np.zeros(shape=(N,N))
	Omatriz = np.zeros(shape=(N,N))
	for i in range(0,N):
		for j in range(0,N):
			matriz[i,j] = (int(FU1[mi2ai(i,j,N)].solution_value()))
			conta +=(int(FU1[mi2ai(i,j,N)].solution_value()))
			#print(int(FU1[mi2ai(i,j,N)].solution_value()))
	for i in range(0,N):
		for j in range(0,N):
			if i != j:
				matriz[i,j] = (int(FU1[mi2ai(i,j,N)].solution_value()))
				conta +=(int(FU1[mi2ai(i,j,N)].solution_value()))
				#print(int(FU1[mi2ai(i,j,N)].solution_value()))
				if int(FU1[mi2ai(i,j,N)].solution_value()) ==1:
					matriz[i,i] = 0
					matriz[j,j] = 0
					
	usuario_atendido = list(DF1.columns)
	tot = 0
	ftot = 0
	outage = 0
	NomaP= 0
	FNomaP = 0
	print(f'Conta BASELINE = {conta}')
	for i in range(0,N):
		for j in range(0,N):
			
			if matriz[i,j] ==1:
				if i == j:
					Omatriz[i,j]=1
					Fmatriz[i,j]=1
					#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
					#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
					usuario_atendido.remove(DF1.columns[j])
					tot +=Baseline[i,i]
					ftot += Baseline[i,i]
					#print(Aloc[i,j])
					#ftot += FNOMA.iloc[i,j]
				else:
					#print(f'NOMA Pair {pair} Near  User: {FU[j]}, data rate = {Aloc[j,j]}') 
					#print(f'NOMA Pair {pair} Far  User: {FU[i]}, data rate = {DF_NOMA.iloc[i,j]}')
					NomaP +=1
					#print(f'FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
					#print(f'FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
					#print(f'Gain over OMA:{(Aloc.iloc[i,j]/np.diag(Aloc)[j])*100}% ') 
					#print(Aloc[i,j])
					
					
					tot +=Baseline[i,j]
					if DF3.iloc[i,j] >= Baseline[i,i] and DF4.iloc[j,j] >= Baseline[j,j]:
						#print(f'alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
						#print(f'alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
						FNomaP +=1
						ftot += DF4.iloc[i,j]
						ftot += DF3.iloc[j,j]
						#print(Aloc[i,j])
						Fmatriz[i,j]=1
						#usuario_atendido.remove(DF_NOMA.columns[j])
						#usuario_atendido.remove(DF_NOMA.index[i])
						
					else:
						#print(f'Não alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[j,j]}') 
						#print(f'Não alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[i,i]}')
						outage +=1
						Fmatriz[i,i]=1
						Fmatriz[j,j]=1
						Fmatriz[i,j]=0
						#print(Aloc[i,j])
						#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
						#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
						#usuario_atendido.remove(DF_NOMA.columns[j])
						tot +=Baseline[j,i]
						ftot += Baseline[i,i]
						ftot += Baseline[j,j]
						pass
					pair = pair +1
			else:
				Omatriz[i,i]=1
	#print(matriz)
	#print(matriz1)
	#print(Omatriz)
	#print(Fmatriz)

	print(f'Fixed PA NOMA SumRate = {ftot}')
	#print('BL Total SumRate =', np.sum(np.multiply(Baseline,matriz)))
	#print(f'OMA Total SumRate = {np.sum(np.sum(np.diag(Baseline)))}')
	#print('AHNOMA SumRate2 =', np.sum(np.multiply(IM,matriz)))
	#print(f'Base Line = {sum(Channel_Capacity)}')
	return {'FNOMA_Matrix':Fmatriz,'Baseline_Matriz':matriz,'matriz':matriz1,'OMA':np.sum(np.sum(np.diag(Baseline))),'Baseline_NOMA': np.sum(np.multiply(matriz,(Baseline))),'AHNOMA':np.sum(np.multiply(matriz1,(IM))),'FixNOMA':ftot,'NOMA_PAIRS':NomaP,'FNOMA_PAIRS':FNomaP,'OUTAGE':outage,'Max_Capacity':sum(Channel_Capacity),'Baseline':Baseline, 'IM':IM}


In [33]:

Transmission = TA(DF0=pd.read_csv('0DF.csv',index_col=0),DF1=pd.read_csv('0DF1.csv',index_col=0),DF2=pd.read_csv('0DF2.csv',index_col=0),DF3=pd.read_csv('0DF3.csv',index_col=0),DF4=pd.read_csv('0DF4.csv',index_col=0),DF5=pd.read_csv('Baseline.csv',index_col=0))

[27.04546747  5.80187587  2.14958067  9.94127582  3.29491536  4.55661603
  7.97926811 31.93063028 21.12375684 13.38465163]
Conta AHNOMA = 10
Solution:
Valor objetivo BaseLine = 111.04241370246028
Valor objetivo AHNOMA = 109.16270979458221
Conta BASELINE = 10
Fixed PA NOMA SumRate = 84.42382261611624


In [34]:
#print(Transmission['matriz'])
#print(Transmission['Baseline_Matriz'])
par=0
for i in range(len(Transmission['Baseline_Matriz'])):
    for j in range(len(Transmission['Baseline_Matriz'])):
        if (Transmission['Baseline_Matriz'][i,j] ==1) and (i!=j):
            par+=1

print(par)
print(Transmission['Baseline_NOMA'])      
print(Transmission['AHNOMA'])  

3
111.04241370246027
109.16270979458218


In [35]:
def calculo(matriz):
    N=len(matriz)
    soma=0
    for i in range(N):
        for j in range(N):
            if i==j:
                if matriz[i,j]==1:
                    soma +=1
                else:
                    pass
            else:
                if matriz[i,j]==1:
                    soma +=2
                else:
                    pass

    return soma

print(np.multiply((Transmission['Baseline_Matriz']),np.ceil(Transmission['Baseline'])))
print(np.sum(np.multiply((Transmission['Baseline_Matriz']),(Transmission['Baseline']))))
#print(Transmission['Baseline_Matriz'])
print(np.multiply((Transmission['matriz']),np.ceil(Transmission['IM'])))
print(np.sum(np.multiply((Transmission['matriz']),(Transmission['IM']))))
#print(Transmission['matriz'])
#print(np.count_nonzero(np.multiply((Transmission['matriz']),(IM))))



[[ 0.  0. 28.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  8.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 32.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 22.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.  0.  0.]]
111.04241370246027
[[ 0.  0. 28.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 32.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 22.  0.]
 [ 0.  0.  0.  0. 14.  0.  0.  0.  0.  0.]]
109.16270979458218


In [36]:
Transmission['Max_Capacity']

127.20803807530208

In [41]:
calculo(Transmission['matriz'])

10

In [38]:
solver1 = pywraplp.Solver.CreateSolver('SCIP')
FU = []
for i in range(0,N):
	for j in range(0,N):
		FU.append(solver1.IntVar(0, 1,f'FU_{i}_{j}'))
print ('Numero de variaveis =', solver1.NumVariables())

head = 1

for j in range(N):
	ct = solver1.Constraint(1,1,str(head))
	print(f'Restrição {head}:')
	for i in range(N):
		if i == j:
			ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
			print(f'{FU[mi2ai(j,i,N)]}+',end='')
		else:
			ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
			print(f'{FU[mi2ai(j,i,N)]}+',end='')
			ct.SetCoefficient(FU[mi2ai(i,j,N)], 1)
			if i == N-1:
				print(f'{FU[mi2ai(i,j,N)]}')
			else:
				print(f'{FU[mi2ai(i,j,N)]}+',end='')
	head +=1	

ct = solver1.Constraint(N,N,str(head))
print(f'Restrição {head}')
for i in range(N):
	for j in range(N):
		if i ==j:
			ct.SetCoefficient(FU[mi2ai(i,j,N)], 1)
		else:
			ct.SetCoefficient(FU[mi2ai(i,j,N)], 2)
			
		if i  == N-1 and j ==N-1:
			print(f'{FU[mi2ai(i,j,N)]} == {N}')
		else:
			print(f'{FU[mi2ai(i,j,N)]}+',end='')

			
# #Executaremos o solver
objective1 = solver1.Objective()
for j in range(N):
    for i in range(N):
        objective1.SetCoefficient(FU[mi2ai(i,j,N)], Baseline[i,j])

        
           
        
		#ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
objective1.SetMaximization()

solver1.Solve()



Numero de variaveis = 100
Restrição 1:
FU_0_0+FU_0_1+FU_1_0+FU_0_2+FU_2_0+FU_0_3+FU_3_0+FU_0_4+FU_4_0+FU_0_5+FU_5_0+FU_0_6+FU_6_0+FU_0_7+FU_7_0+FU_0_8+FU_8_0+FU_0_9+FU_9_0
Restrição 2:
FU_1_0+FU_0_1+FU_1_1+FU_1_2+FU_2_1+FU_1_3+FU_3_1+FU_1_4+FU_4_1+FU_1_5+FU_5_1+FU_1_6+FU_6_1+FU_1_7+FU_7_1+FU_1_8+FU_8_1+FU_1_9+FU_9_1
Restrição 3:
FU_2_0+FU_0_2+FU_2_1+FU_1_2+FU_2_2+FU_2_3+FU_3_2+FU_2_4+FU_4_2+FU_2_5+FU_5_2+FU_2_6+FU_6_2+FU_2_7+FU_7_2+FU_2_8+FU_8_2+FU_2_9+FU_9_2
Restrição 4:
FU_3_0+FU_0_3+FU_3_1+FU_1_3+FU_3_2+FU_2_3+FU_3_3+FU_3_4+FU_4_3+FU_3_5+FU_5_3+FU_3_6+FU_6_3+FU_3_7+FU_7_3+FU_3_8+FU_8_3+FU_3_9+FU_9_3
Restrição 5:
FU_4_0+FU_0_4+FU_4_1+FU_1_4+FU_4_2+FU_2_4+FU_4_3+FU_3_4+FU_4_4+FU_4_5+FU_5_4+FU_4_6+FU_6_4+FU_4_7+FU_7_4+FU_4_8+FU_8_4+FU_4_9+FU_9_4
Restrição 6:
FU_5_0+FU_0_5+FU_5_1+FU_1_5+FU_5_2+FU_2_5+FU_5_3+FU_3_5+FU_5_4+FU_4_5+FU_5_5+FU_5_6+FU_6_5+FU_5_7+FU_7_5+FU_5_8+FU_8_5+FU_5_9+FU_9_5
Restrição 7:
FU_6_0+FU_0_6+FU_6_1+FU_1_6+FU_6_2+FU_2_6+FU_6_3+FU_3_6+FU_6_4+FU_4_6+FU_6_5+FU_5_6+F

0

In [39]:
index = 0
for i in range(N):
    for j in range(N):
        print(f'{FU[mi2ai(i,j,N)]}={FU[index].solution_value()}')
        index+=1


FU_0_0=0.0
FU_0_1=-0.0
FU_0_2=1.0
FU_0_3=-0.0
FU_0_4=-0.0
FU_0_5=-0.0
FU_0_6=0.0
FU_0_7=0.0
FU_0_8=0.0
FU_0_9=-0.0
FU_1_0=0.0
FU_1_1=0.0
FU_1_2=0.0
FU_1_3=1.0
FU_1_4=0.0
FU_1_5=-0.0
FU_1_6=0.0
FU_1_7=0.0
FU_1_8=0.0
FU_1_9=0.0
FU_2_0=-0.0
FU_2_1=-0.0
FU_2_2=0.0
FU_2_3=-0.0
FU_2_4=-0.0
FU_2_5=-0.0
FU_2_6=-0.0
FU_2_7=0.0
FU_2_8=0.0
FU_2_9=-0.0
FU_3_0=0.0
FU_3_1=-0.0
FU_3_2=-0.0
FU_3_3=0.0
FU_3_4=0.0
FU_3_5=-0.0
FU_3_6=0.0
FU_3_7=0.0
FU_3_8=0.0
FU_3_9=0.0
FU_4_0=-0.0
FU_4_1=-0.0
FU_4_2=0.0
FU_4_3=-0.0
FU_4_4=0.0
FU_4_5=-0.0
FU_4_6=0.0
FU_4_7=0.0
FU_4_8=0.0
FU_4_9=-0.0
FU_5_0=0.0
FU_5_1=-0.0
FU_5_2=0.0
FU_5_3=0.0
FU_5_4=0.0
FU_5_5=1.0
FU_5_6=0.0
FU_5_7=0.0
FU_5_8=0.0
FU_5_9=0.0
FU_6_0=-0.0
FU_6_1=-0.0
FU_6_2=0.0
FU_6_3=-0.0
FU_6_4=-0.0
FU_6_5=-0.0
FU_6_6=1.0
FU_6_7=0.0
FU_6_8=-0.0
FU_6_9=-0.0
FU_7_0=-0.0
FU_7_1=-0.0
FU_7_2=-0.0
FU_7_3=-0.0
FU_7_4=-0.0
FU_7_5=-0.0
FU_7_6=-0.0
FU_7_7=1.0
FU_7_8=0.0
FU_7_9=-0.0
FU_8_0=-0.0
FU_8_1=-0.0
FU_8_2=-0.0
FU_8_3=-0.0
FU_8_4=-0.0
FU_8_5=-0.0
FU_8_6=0.0


In [40]:

print('Solution:')
print('Valor objetivo =', (objective1.Value()))
print('Valor objetivo =', (objective.Value()))
pair = 0
matriz = np.zeros(shape=(N,N))
Fmatriz = np.zeros(shape=(N,N))
Omatriz = np.zeros(shape=(N,N))
for i in range(0,N):
    for j in range(0,N):
        matriz[i,j] = (int(FU[mi2ai(i,j,N)].solution_value()))
for i in range(0,N):
    for j in range(0,N):
        if i != j:
            matriz[i,j] = (int(FU[mi2ai(i,j,N)].solution_value()))
            if int(FU[mi2ai(i,j,N)].solution_value()) ==1:
                '''matriz[i,i] = 0
                matriz[j,j] = 0'''
                pass
usuario_atendido = list(DF_OMA.columns)
tot = 0
ftot = 0
outage = 0
NomaP= 0
FNomaP = 0

for i in range(0,N):
	for j in range(0,N):
		
		if matriz[i,j] ==1:
			if i == j:
				Omatriz[i,j]=1
				Fmatriz[i,j]=1
				#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
				#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
				usuario_atendido.remove(DF_OMA.columns[j])
				tot +=DF_NOMA[i,i]
				ftot += DF_NOMA[i,i]
				#print(Aloc[i,j])
				#ftot += FNOMA.iloc[i,j]
			else:
				#print(f'NOMA Pair {pair} Near  User: {FU[j]}, data rate = {Aloc[j,j]}') 
				#print(f'NOMA Pair {pair} Far  User: {FU[i]}, data rate = {DF_NOMA.iloc[i,j]}')
				NomaP +=1
				#print(f'FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
				#print(f'FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
				#print(f'Gain over OMA:{(Aloc.iloc[i,j]/np.diag(Aloc)[j])*100}% ') 
				#print(Aloc[i,j])
				
				
				tot +=Baseline[i,j]
				if FNOMA.iloc[i,j] >= DF_NOMA[i,i] and NUFNOMA.iloc[j,j] >= DF_NOMA[j,j]:
					#print(f'alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}') 
					#print(f'alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}')
					FNomaP +=1
					ftot += NUFNOMA.iloc[i,j]
					ftot += FNOMA.iloc[j,j]
					#print(Aloc[i,j])
					Fmatriz[i,j]=1
					#usuario_atendido.remove(DF_NOMA.columns[j])
					#usuario_atendido.remove(DF_NOMA.index[i])
					 
				else:
					#print(f'Não alocado:FIXED NOMA Pair {pair} Near  User: {FU[j]}, data rate = {NUFNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[j,j]}') 
					#print(f'Não alocado:FIXED NOMA Pair {pair} Far  User: {FU[i]}, data rate = {FNOMA.iloc[i,j]}, Alocado Ortogonal: {Aloc[i,i]}')
					outage +=1
					Fmatriz[i,i]=1
					Fmatriz[j,j]=1
					Fmatriz[i,j]=0
					#print(Aloc[i,j])
					#print(f'OMA User: {DF_NOMA.columns[j]}, data rate = {Aloc[i,i]}')
					#print(f'Used {(Aloc[i,j]/np.diag(Aloc)[i])*100}% from Shannon Channel Capacity')
					#usuario_atendido.remove(DF_NOMA.columns[j])
					tot +=Baseline[j,i]
					ftot += Baseline[i,i]
					ftot += Baseline[j,j]
					pass
				pair = pair +1
		else:
			Omatriz[i,i]=1
print(matriz)
print(Omatriz)
print(Fmatriz)
print(matriz1)
print(f'Fixed PA NOMA SumRate = {ftot}')
print('Total SumRate =', np.sum(np.multiply(Baseline,matriz)))
print(f'OMA Total SumRate = {np.sum(np.sum(np.diag(Baseline)))}')
print('Total SumRate2 =', np.sum(np.multiply(IM,matriz1)))
print(f'Base Line = {sum(Channel_Capacity)}')


Solution:
Valor objetivo = 111.04241370246028


NameError: name 'objective' is not defined

In [ ]:
sum(Baseline)

In [ ]:
sum(IM)

In [ ]:
Baseline

In [ ]:
IM

In [ ]:
OMA.append(np.sum(np.sum(np.diag(Aloc))))
NOMA.append(np.sum(np.sum(Aloc*matriz)))
FixNOMA.append(ftot)
NOMA_PAIRS.append(NomaP)
FNOMA_PAIRS.append(FNomaP)
OUTAGE.append(outage)

In [ ]:
sla['OMA Sum rate'] = OMA
sla['Architecture Sum rate'] = NOMA
sla['Fixed NOMA Sum rate'] = FixNOMA
sla['Fixed NOMA Pairs'] = FNOMA_PAIRS
sla['NOMA Pairs'] = NOMA_PAIRS
sla['Fixed NOMA Outage'] = OUTAGE

In [ ]:
#Aloc #sumrate

In [ ]:
#DF_NOMA #achievable data rate

In [ ]:
#FNOMA
#DF_OMA #max channel capacity

In [ ]:
len(sla['OMA Sum rate'])

In [ ]:
sla['OMA Sum rate'][-1]

In [ ]:
sla['Architecture Sum rate'][-1]

In [ ]:
sla['Fixed NOMA Sum rate'][-1]

In [ ]:
KCT = pd.DataFrame(sla)
KCT.to_csv('Arq.csv',)

In [ ]:
objective1 = solver.Objective()
for j in range(N):
    #objective.SetCoefficient(FU[mi2ai(i,i,N)], 1)
    for i in range(N):
        objective1.SetCoefficient(FU[mi2ai(i,j,N)], (DF_NOMA[i,j]))
        #ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
objective1.SetMaximization()

# #Executaremos o solver
solver.Solve()

In [ ]:
objective1 = solver.Objective()
for j in range(N):
    #objective.SetCoefficient(FU[mi2ai(i,i,N)], 1)
    for i in range(N):
        objective1.SetCoefficient(FU[mi2ai(i,j,N)], (DF_NOMA[i,j]))
        #ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
objective1.SetMaximization()

# #Executaremos o solver
solver.Solve()

In [ ]:
objective1 = solver.Objective()
for j in range(N):
    #objective.SetCoefficient(FU[mi2ai(i,i,N)], 1)
    for i in range(N):
        objective1.SetCoefficient(FU[mi2ai(i,j,N)], (DF_NOMA[i,j]))
        #ct.SetCoefficient(FU[mi2ai(j,i,N)], 1)
objective1.SetMaximization()

# #Executaremos o solver
solver.Solve()

In [ ]:

Transmission = TA(DF0=pd.read_csv('0DF.csv',index_col=0),DF1=pd.read_csv('0DF1.csv',index_col=0),DF2=pd.read_csv('0DF2.csv',index_col=0),DF3=pd.read_csv('0DF3.csv',index_col=0),DF4=pd.read_csv('0DF4.csv',index_col=0),DF5=pd.read_csv('Baseline.csv',index_col=0))